---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-admin
rules:
  - apiGroups: [""]
    resources:
      - "pods"
      - "pods/exec"
      - "services"
      - "endpoints"
      - "persistentvolumeclaims"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "delete"
      - "patch"
      - "update"
  - apiGroups: ["apps"]
    resources:
      - "deployments"
      - "replicasets"
      - "statefulsets"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "delete"
      - "patch"
      - "update"
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - "roles"
      - "rolebindings"
    verbs:
      - "get"
      - "list"
      - "create"
      - "delete"
      - "patch"
      - "update"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-admin
  namespace: jenkins

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-admin
subjects:
- kind: ServiceAccount
  name: jenkins-admin
  namespace: jenkins
  