---
- name: Example playbook
  hosts: localhost
  gather_facts: false
  
  vars_files:
    - "{{ playbook_dir }}/../example/group_vars/general-vars.yml"
    - "{{ playbook_dir }}/../example/group_vars/example-vault"

  tasks:
    - name: Show variable
      ansible.builtin.debug:
        msg: "myvar: {{ myvar }}"

    - name: Show secret
      ansible.builtin.debug:
        msg: "mysecret: {{ mysecret }}"

    - name: Check kubectl version
      ansible.builtin.command: kube version
      register: kubectl_version
      changed_when: false

    - name: Print kubectl version
      ansible.builtin.debug:
        msg: "{{ kubectl_version }}"

    - name: Copy example Jinja template
      