---
- name: Example playbook
  hosts: localhost
  gather_facts: false
  
  vars_files:
    - "{{ playbook_dir }}/../example/group_vars/general-vars.yml"
    - "{{ playbook_dir }}/../example/group_vars/example-vault"

  tasks:
    - name: Show variable
      ansible.builtin.debug:
        msg: "myvar: {{ myvar }}"

    - name: Show secret
      ansible.builtin.debug:
        msg: "mysecret: {{ mysecret }}"

    - name: Check Docker version
      ansible.builtin.command: docker version
      register: docker_version 
      changed_when: false

    - name: Print Docker version
      ansible.builtin.debug:
        msg: "{{ docker_version | to_nice_json }}"

    - name: Copy example Nginx config template
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../example/template/example-template.j2"
        dest: "{{ playbook_dir }}/../tmp/nginx.conf"
        mode: "0600"

    - name: Delete Nginx config file
      ansible.builtin.file:
        path: "{{ playbook_dir }}/../tmp/nginx.conf"
        state: absent 
